services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: kysely_db
      POSTGRES_USER: kysely_user
      POSTGRES_PASSWORD: kysely_pass
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - '4001:8080'
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
volumes:
  db_data:
